# Libreria NumPy

NumPy es una libreria para python que permite trabajar con vectores y matrices multidimensionales. Es una libreria especialisada en cálculo numerico y cuenta con una gran colección de funciones para operar dichos vectores y/o matrices. Es una de las librerias más populares y utilizdas en python por lo que es fundamental tener conocimiento sobre ella.

Instalación:

    pip install numpy

In [105]:
import numpy as np

#### Creación de vectores y matrices a partir de listas

In [106]:
## Vector 1D
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

## Matriz 2D
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


#### Porpiedades de un vector o matriz

In [107]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape - Forma:", arr.shape)
print("Numero de dimensiones:", arr.ndim)
print("Tamaño:", arr.size) ## Producto de las dimensiones del vector
print("Tipo:", arr.dtype)

Shape - Forma: (2, 3)
Numero de dimensiones: 2
Tamaño: 6
Tipo: int32


#### Modificar dimensiones del vector

In [108]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
reshaped_arr = arr.reshape(3, 2)
print("Nuevo vector:\n", reshaped_arr)

Nuevo vector:
 [[1 2]
 [3 4]
 [5 6]]


#### Indexación y Particiones

In [109]:
arr = np.array([1, 2, 3, 4, 5])

# Indexing
print("Elemento en indice 1:", arr[1])

# Slicing
print("Elementos en indices 1 a 3:", arr[1:4])

# 2D array indexing and slicing
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("Elemento en fila 1, columna 2:", arr2[1, 2])
print("Primera fila:", arr2[0, :])
print("Primera columna:", arr2[:, 0])

Elemento en indice 1: 2
Elementos en indices 1 a 3: [2 3 4]
Elemento en fila 1, columna 2: 6
Primera fila: [1 2 3]
Primera columna: [1 4]


#### Funciones basicas

In [110]:
## Vector de ceros
zeros = np.zeros((3, 3))
print("Array of Zeros:\n", zeros)

## Vector de unos
ones = np.ones((2, 4))
print("Array of Ones:\n", ones)

## Vector con un rango de valores
range_array = np.arange(0, 10, 2)  # Inicio, Final, Paso
print("Range Array:", range_array)

## Vector con valores separados de igual manera
linspace_array = np.linspace(0, 1, 5)  ## Inicio, Final, numero de valores
print("Linspace Array:", linspace_array)


Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]


#### Operaciones básicas

In [111]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

## Element-wise addition
print("Suma elemento a elemento:", arr1 + arr2)

## Element-wise multiplication
print("Multiplicación elemento a elemento:", arr1 * arr2)

## Dot product
print("Producto vectorial:", np.dot(arr1, arr2))

## Sum of all elements
print("Suma de todos los elementos:", np.sum(arr1))

## Transpose of a matrix
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("Transpuesta opción 1:\n", arr2d.T)
print("Transpuesta opción 2:\n", np.transpose(arr2d))

Suma elemento a elemento: [5 7 9]
Multiplicación elemento a elemento: [ 4 10 18]
Producto vectorial: 32
Suma de todos los elementos: 6
Transpuesta opción 1:
 [[1 4]
 [2 5]
 [3 6]]
Transpuesta opción 2:
 [[1 4]
 [2 5]
 [3 6]]


#### Funciones universales (ufunc) para operaciones elemento a elemento (Element-wise operations)

In [112]:
arr = np.array([1, 2, 3, 4, 5])

## Raiz cuadrada
print("Raiz cuadrada:", np.sqrt(arr))

## Exponencial
print("Exponencial:", np.exp(arr))

## Funciones trigonometricas
print("Seno:", np.sin(arr))
print("Coseno:", np.cos(arr))
print("Tangente:", np.tan(arr))
print("Tangente hiperbolica:", np.tanh(arr))

print("Seno Inverso:", np.arcsin(0.1))
print("Coseno inverso:", np.arccos(0.1))
print("Tangente inversa:", np.arctan(0.1))
print("Tangente inversa hiperbolica:", np.arctanh(0.1))
print("Tangente inversa 2:", np.arctan2(0.1, 0.1)) ## (Y, X)

Raiz cuadrada: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Seno: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Coseno: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Tangente: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
Tangente hiperbolica: [0.76159416 0.96402758 0.99505475 0.9993293  0.9999092 ]
Seno Inverso: 0.1001674211615598
Coseno inverso: 1.4706289056333368
Tangente inversa: 0.09966865249116204
Tangente inversa hiperbolica: 0.1003353477310756
Tangente inversa 2: 0.7853981633974483


#### Funciones de agregación y calculos estadisticos

In [113]:
arr = np.array([1, 2, 3, 4, 5])

# Minimo
print("Minimo:", np.min(arr))

# Maximo
print("Maximo:", np.max(arr))

# Promedio
print("Promedio:", np.mean(arr))

# Media
print("Media:", np.median(arr))

# Desviación estandar
print("Desviación estandar:", np.std(arr))

Minimo: 1
Maximo: 5
Promedio: 3.0
Media: 3.0
Desviación estandar: 1.4142135623730951
